<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Globals
{

    public function userTypes()
    {
        return array("1" => "Super Admin", "2" => "Chairman", "3" => "Principal/Director", '4' => "Dean SA", '5' => "Admission Staff", '6' => "Accounts Admin", '7' => "Accounts Staff", '8'=>"COE");
    }

    public function enquiryStatus()
    {
        return array("1" => "New", "2" => "Working", "3" => "On-Hold", "4" => "Archived", "5" => "Bad Data", "6" => "Admitted", "7" => "Seat Blocked");
    }

    public function enquiryStatusColor()
    {
        return array("1" => "primary", "2" => "success", "3" => "warning", "4" => "danger", "5" => "danger", "6" => "info", "7" => "danger");
    }

    public function admissionStatus()
    {
        return array("1" => "Processing", "2" => "Submitted", "3" => "On-Hold", "4" => "Confirmed", "5" => "Rejected", "6" => "Canceled", "7" => "Archived");
    }

    public function admissionStatusColor()
    {
        return array("1" => "info", "2" => "primary", "3" => "warning", "4" => "success", "5" => "danger", "6" => "danger", "7" => "danger");
    }

    public function transactionTypes()
    {

        return array("1" => "Cash", "2"=>"DD", "3"=>"Online Payment", "4"=>"Online Transfer");

    }

    public function currentAcademicYear()
    {

        $details = "2024-2025";
        return $details;
    }

    public function academicYear()
    {

        $details = array();
        // for($i = 2020; $i <= date('Y'); $i++){
        for ($i = 2024; $i < 2025; $i++) {
            $iNext = $i + 1;
            $details[$i . '-' . $iNext] = $i . '-' . $iNext;
        }
        return $details;
    }
    public function courses()
    {
        return array("CS" => "CS", "EEE" => "EEE", "EIE" => "EIE", "ME" => "ME", "ECE" => "ECE", "AE" => "AE");
    }

    public function courseFees()
    {

        $details = array(
            "CS" => array("Q1" => 20000, "Q2" => 11000),
            "EEE" => array("Q1" => 20000, "Q2" => 11000),
            "EIE" => array("Q1" => 20000, "Q2" => 11000)

        );

        return $details;
    }
    public function languages()
    {
        return array(
            "KANNADA" => "KANNADA",
            "ENGLISH" => "ENGLISH",
            "HINDI" => "HINDI",
            "SANSKRIT" => "SANSKRIT",
            "TAMIL" => "TAMIL",
            "TELUGU" => "TELUGU",
            "URDU" => "URDU"
        );
    }

    public function admissionBased()
    {
        return array(
            "PUC" => "PUC",
            "DIPLOMA" => "DIPLOMA",
            "GTTC" => "GT&TC"
        );
    }
    
    public function quota()
    {
        return array(
            "KEA-CET(GOVT)" => "KEA-CET(GOVT)",
            "COMED-K" => "COMED-K",
            "MGMT" => "MGMT",
            "KEA-SNQ" => "KEA-SNQ",
            "J&K (Non Karnataka)" => "J&K (Non Karnataka)",
            "GOI (Non Karnataka)" => "GOI (Non Karnataka)",
            "KEA-CET(LATERAL)" => "KEA-CET(LATERAL)",
            "MGMT-COMEDK" => "MGMT-COMEDK",
            "MGMT-LATERAL" => "MGMT-LATERAL",
        );
    }

    public function sub_quota()
    {
        return array(
           
            "Aided" => "Aided",
            "UnAided" => "UnAided"
        );
    }

    public function college_code()
    {
        return array(
            "EO24-AIDED" => "EO24-AIDED",
            "EO47-UNAIDED" => "EO47-UNAIDED",
            "E079-COMED-K" => "E079-COMED-K"
        );
    }

    public function college_codes()
    {
        return array(
            "Aided" => "EO24-AIDED",
            "UnAided" => "EO47-UNAIDED",
            "COMED-K" => "E079-COMED-K"
        );
    }

    public function category()
    {
        return array(
            '1G'=>'1G',
            '1GH'=>'1GH',
            '1GHR'=>'1GHR',
            '1GK'=>'1GK',
            '1GR'=>'1GR',
            '1H'=>'1H',
            '1K'=>'1K',
            '1R'=>'1R',
            '2A'=>'2A',
            '2AG'=>'2AG',
            '2AGH'=>'2AGH',
            '2AGK'=>'2AGK',
            '2AGR'=>'2AGR',
            '2AGRH'=>'2AGRH',
            '2AGRK'=>'2AGRK',
            '2AH'=>'2AH',
            '2AK'=>'2AK',
            '2AR'=>'2AR',
            '2ARH'=>'2ARH',
            '2B'=>'2B',
            '2BG'=>'2BG',
            '2BGK'=>'2BGK',
            '2BGRK'=>'2BGRK',
            '2BK'=>'2BK',
            '2BR'=>'2BR',
            '2GHR'=>'2GHR',
            '3A'=>'3A',
            '3AG'=>'3AG',
            '3AGK'=>'3AGK',
            '3AGR'=>'3AGR',
            '3AGRK'=>'3AGRK',
            '3AH'=>'3AH',
            '3AR'=>'3AR',
            '3B'=>'3B',
            '3BG'=>'3BG',
            '3BGH'=>'3BGH',
            '3BGK'=>'3BGK',
            '3BGRK'=>'3BGRK',
            '3BH'=>'3BH',
            '3BK'=>'3BK',
            '3BR'=>'3BR',
            '3BRK'=>'3BRK',
            '3GHR'=>'3GHR',
            'AGL'=>'AGL',
            // 'COMED-K'=>'COMED-K',
            'D'=>'D',
            'GAH'=>'GAH',
            'GM'=>'GM',
            'GMH'=>'GMH',
            'GMK'=>'GMK',
            'GMR'=>'GMR',
            'GMRH'=>'GMRH',
            'GMRK'=>'GMRK',
            // 'GOI'=>'GOI',
            'IG'=>'IG',
            // 'J&K'=>'J&K',
            // 'NAIDU'=>'NAIDU',
            'NCC'=>'NCC',
            'NKR'=>'NKR',
            'NRI'=>'NRI',
            'OBC'=>'OBC',
            'PH'=>'PH',
            'SC'=>'SC',
            'SCG'=>'SCG',
            'SCGK'=>'SCGK',
            'SCGR'=>'SCGR',
            'SCGRH'=>'SCGRH',
            'SCGRK'=>'SCGRK',
            'SCH'=>'SCH',
            'SCK'=>'SCK',
            'SCR'=>'SCR',
            'SCRH'=>'SCRH',
            'SG'=>'SG',
            'SNQ'=>'SNQ',
            'SPO'=>'SPO',
            'SPORTS'=>'SPORTS',
            'ST'=>'ST',
            'STG'=>'STG',
            'STGH'=>'STGH',
            'STGRK'=>'STGRK',
            'STH'=>'STH',
            'STK'=>'STK',
            'STR'=>'STR',
            'XD'=>'XD',
        );
    }

    public function category_claimed()
    {
        return array(
            '1G'=>'1G',
            '1GH'=>'1GH',
            '1GHR'=>'1GHR',
            '1GK'=>'1GK',
            '1GR'=>'1GR',
            '1H'=>'1H',
            '1K'=>'1K',
            '1R'=>'1R',
            '2A'=>'2A',
            '2AG'=>'2AG',
            '2AGH'=>'2AGH',
            '2AGK'=>'2AGK',
            '2AGR'=>'2AGR',
            '2AGRH'=>'2AGRH',
            '2AGRK'=>'2AGRK',
            '2AH'=>'2AH',
            '2AK'=>'2AK',
            '2AR'=>'2AR',
            '2ARH'=>'2ARH',
            '2B'=>'2B',
            '2BG'=>'2BG',
            '2BGK'=>'2BGK',
            '2BGRK'=>'2BGRK',
            '2BK'=>'2BK',
            '2BR'=>'2BR',
            '2GHR'=>'2GHR',
            '3A'=>'3A',
            '3AG'=>'3AG',
            '3AGK'=>'3AGK',
            '3AGR'=>'3AGR',
            '3AGRK'=>'3AGRK',
            '3AH'=>'3AH',
            '3AR'=>'3AR',
            '3B'=>'3B',
            '3BG'=>'3BG',
            '3BGH'=>'3BGH',
            '3BGK'=>'3BGK',
            '3BGRK'=>'3BGRK',
            '3BH'=>'3BH',
            '3BK'=>'3BK',
            '3BR'=>'3BR',
            '3BRK'=>'3BRK',
            '3GHR'=>'3GHR',
            'GAH'=>'GAH',
            'GM'=>'GM',
            'GMH'=>'GMH',
            'GMK'=>'GMK',
            'GMR'=>'GMR',
            'GMRH'=>'GMRH',
            'GMRK'=>'GMRK',   
            'IG'=>'IG',
            'SC'=>'SC',
            'SCG'=>'SCG',
            'SCGK'=>'SCGK',
            'SCGR'=>'SCGR',
            'SCGRH'=>'SCGRH',
            'SCGRK'=>'SCGRK',
            'SCH'=>'SCH',
            'SCK'=>'SCK',
            'SCR'=>'SCR',
            'SCRH'=>'SCRH',
            'ST'=>'ST',
            'STG'=>'STG',
            'STGH'=>'STGH',
            'STGRK'=>'STGRK',
            'STH'=>'STH',
            'STK'=>'STK',
            'STR'=>'STR',
           
        );
    }


    public function states(){
        return array(
        "AP" => "Andhra Pradesh",
        "AR" => "Arunachal Pradesh",
        "AS" => "Assam",
        "BR" => "Bihar",
        "CT" => "Chhattisgarh",
        "GA" => "Gujarat",
        "HR" => "Haryana",
        "HP" => "Himachal Pradesh",
        "JK" => "Jammu and Kashmir",
        "GA" => "Goa",
        "JH" => "Jharkhand",
        "KA" => "Karnataka",
        "KL" => "Kerala",
        "MP" => "Madhya Pradesh",
        "MH" => "Maharashtra",
        "MN" => "Manipur",
        "ML" => "Meghalaya",
        "MZ" => "Mizoram",
        "NL" => "Nagaland",
        "OR" => "Odisha",
        "PB" => "Punjab",
        "RJ" => "Rajasthan",
        "SK" => "Sikkim",
        "TN" => "Tamil Nadu",
        "TG" => "Telangana",
        "TR" => "Tripura",
        "UT" => "Uttarakhand",
        "UP" => "Uttar Pradesh",
        "WB" => "West Bengal",
        "AN" => "Andaman and Nicobar Islands",
        "CH" => "Chandigarh",
        "DN" => "Dadra and Nagar Haveli",
        "DD" => "Daman and Diu",
        "DL" => "Delhi",
        "LD" => "Lakshadweep",
        "PY" => "Puducherry");
    }

    public function medium_of_instruction()
    {
        return array(
           
            "English" => "English",
            "Kannada" => "Kannada",
            "Hindi" => "Hindi"
        );
    }

    public function religion()
    {
        return array(
           
            "Hindu" => "Hindu",
            "Islam" => "Islam",
            "Christian" => "Christian",
            "Sikh" => "Sikh",
            "Parsi" => "Parsi",
            "Jainism" => "Jainism",
            "Others" => "Others"
        );
    }

    public function sslcsubjects()
    {
        return array(
           
            "Sanskrit" => "Sanskrit",
            "English" => "English",
            "Kannada" => "Kannada",
            "Hindi" => "Hindi",
            "Urdu" => "Urdu",
            "Telugu" => "Telugu",
            "Tamil" => "Tamil",
            "Others" => "Others",
            "Mathematics" => "Mthematics",
            "Social Science" => "Social Science",
            "Science" => "Science",
            "Others" => "Others"
        );
    }

    public function pucsubjects()
    {
        return array(
           
            "Sanskrit" => "Sanskrit",
            "English" => "English",
            "Kannada" => "Kannada",
            "Hindi" => "Hindi",
            "Urdu" => "Urdu",
            "Telugu" => "Telugu",
            "Tamil" => "Tamil",
            "French" => "French",
            "Physics" => "Physics",
            "Chemistry" => "Chemistry",
            "Mathematics" => "Mthematics",
            "Computer Science" => "Computer Science",
            "Biology" => "Biology",
            "Electronics" => "Electronics",
            "Others" => "Others"
        );
    }

    public function caste()
    {
        return array(
           
            "24 mane telugu shetty" => "24 mane telugu shetty",
            "2BGK" => "2BGK",
            "3AGRK" => "3AGRK",
            "AADI KARNATAKA" => "AADI KARNATAKA",
            "ACHARI" => "ACHARI",
            "ADI DHRAVIDA" => "ADI DHRAVIDA",
            "ARYA VAISHYA" => "ARYA VAISHYA",
            "ATTE VOKKALU" => "ATTE VOKKALU",
            "AUSALA" => "AUSALA",
            "AVIR" => "AVIR",
            "AYIRI" => "AYIRI",
            "BAANDHI" => "BAANDHI",
            "BADAGI" => "BADAGI",
            "BADIGAR" => "BADIGAR",
            "BADIWADLA" => "BADIWADLA",
            "BAGAADI" => "BAGAADI",
            "BAGADI" => "BAGADI",
            "BAGALI" => "BAGALI",
            "BAGDI" => "BAGDI",
            "BAGGARU" => "BAGGARU",
            "BAHURUPI" => "BAHURUPI",
            "BAILAPATAR" => "BAILAPATAR",
            "BAILPATAR" => "BAILPATAR",
            "BAILU AKKASALI" => "BAILU AKKASALI",
            "BAILU KAMMARA" => "BAILU KAMMARA",
            "BAIRA" => "BAIRA",
            "BAIRAGI" => "BAIRAGI",
            "BAJANIA" => "BAJANIA",
            "BAJANTHRI" => "BAJANTHRI",
            "BAJENIA" => "BAJENIA",
            "BAKAD" => "BAKAD",
            "BAKADRA" => "BAKADRA",
            "BAKUDA" => "BAKUDA",
            "BALAGAI" => "BALAGAI",
            "BALAJIGA" => "BALAJIGA",
            "BALASANTHOSHI" => "BALASANTHOSHI",
            "BALAVALIKAR" => "BALAVALIKAR",
            "BALE" => "BALE",
            "BALE BANAJIGA" => "BALE BANAJIGA",
            "BALE CHETTY" => "BALE CHETTY",
            "BALEGARA" => "BALEGARA",
            "BALIJA" => "BALIJA",
            "BALLALA" => "BALLALA",
            "BALMIKI" => "BALMIKI",
            "BALYAYA" => "BALYAYA",
            "BAMCHA" => "BAMCHA",
            "BANAGARA" => "BANAGARA",
            "BANAJIGA" => "BANAJIGA",
            "BANAJIGA SETTY" => "BANAJIGA SETTY",
            "BANDARI" => "BANDARI",
            "BANDHARI" => "BANDHARI",
            "BANDI" => "BANDI",
            "BANJARA" => "BANJARA",
            "BANJARI" => "BANJARI",
            "BANNA" => "BANNA",
            "BANT" => "BANT",
            "BAORI" => "BAORI",
            "BARDA" => "BARDA",
            "BARGI" => "BARGI",
            "BARIKA" => "BARIKA",
            "BARKI" => "BARKI",
            "BARODIA" => "BARODIA",
            "BASAVI" => "BASAVI",
            "BATHADA" => "BATHADA",
            "BATHAL" => "BATHAL",
            "BATTAL" => "BATTAL",
            "BATTER" => "BATTER",
            "BAVA" => "BAVA",
            "BAVACHA" => "BAVACHA",
            "BAVAJI" => "BAVAJI",
            "BAVANDHI" => "BAVANDHI",
            "BAVANI" => "BAVANI",
            "BAWTAR" => "BAWTAR",
            "BAZIGAR" => "BAZIGAR",
            "BEDA" => "BEDA",
            "BEDA JANGAM," => "BEDA JANGAM,",
            "BEDAR" => "BEDAR",
            "BEDARU" => "BEDARU",
            "BEGADI" => "BEGADI",
            "BELCHAD" => "BELCHAD",
            "BELDAR" => "BELDAR",
            "BELLARA" => "BELLARA",
            "BENDAR" => "BENDAR",
            "BERAD" => "BERAD",
            "BESTHA" => "BESTHA",
            "BESTHAR" => "BESTHAR",
            "BHAAT" => "BHAAT",
            "BHAGALIA" => "BHAGALIA",
            "BHAMBHI" => "BHAMBHI",
            "BHAMBI" => "BHAMBI",
            "BHAMTA" => "BHAMTA",
            "BHANDI VODDAR" => "BHANDI VODDAR",
            "BHANGI" => "BHANGI",
            "BHARDI" => "BHARDI",
            "BHARGI" => "BHARGI",
            "BHARWAD" => "BHARWAD",
            "BHATIAL" => "BHATIAL",
            "BHATRAJU" => "BHATRAJU",
            "BHATTIA" => "BHATTIA",
            "BHAVASAR KSHATRIYA" => "BHAVASAR KSHATRIYA",
            "BHAVIN" => "BHAVIN",
            "BHIL" => "BHIL",
            "BHIL GARASIA" => "BHIL GARASIA",
            "BHILALA" => "BHILALA",
            "BHINE KOYA" => "BHINE KOYA",
            "BHOGAM" => "BHOGAM",
            "BHOI" => "BHOI",
            "BHOMPTA" => "BHOMPTA",
            "BHOMPTRA" => "BHOMPTRA",
            "BHOVI" => "BHOVI",
            "BHOYI" => "BHOYI",
            "BILAPATAR" => "BILAPATAR",
            "BILI MAGGA" => "BILI MAGGA",
            "BILLAVA" => "BILLAVA",
            "BINAPATTA" => "BINAPATTA",
            "BINDLA" => "BINDLA",
            "BINGI" => "BINGI",
            "BOGAD" => "BOGAD",
            "BOGADI" => "BOGADI",
            "BOGAM" => "BOGAM",
            "BOGAR" => "BOGAR",
            "BOGARA" => "BOGARA",
            "BOHROT" => "BOHROT",
            "BOLAHALLALA" => "BOLAHALLALA",
            "BOVI" => "BOVI",
            "BOYA" => "BOYA",
            "BOYI" => "BOYI",
            "BRAHMA KAPALI" => "BRAHMA KAPALI",
            "BRAHMIN" => "BRAHMIN",
            "BRINJARI" => "BRINJARI",
            "BUDBUDKALA" => "BUDBUDKALA",
            "BUDDHISTS" => "BUDDHISTS",
            "BUDGA JANGAM" => "BUDGA JANGAM",
            "BUDUBUDUKI" => "BUDUBUDUKI",
            "BUDUDKI" => "BUDUDKI",
            "BUNDE-BESHTAR" => "BUNDE-BESHTAR",
            "BUNDE-BESTHA" => "BUNDE-BESTHA",
            "BUNT" => "BUNT",
            "BURBURCHA" => "BURBURCHA",
            "BURNED" => "BURNED",
            "BURUD" => "BURUD",
            "BYADA" => "BYADA",
            "BYAGARA" => "BYAGARA",
            "BYARAGI" => "BYARAGI",
            "BYRAGI" => "BYRAGI",
            "CHAKALA" => "CHAKALA",
            "CHAKKAN" => "CHAKKAN",
            "CHAKKILIYAN" => "CHAKKILIYAN",
            "CHAKRASALI" => "CHAKRASALI",
            "CHAKRAVADYA-DASA" => "CHAKRAVADYA-DASA",
            "CHALAVADI" => "CHALAVADI",
            "CHALIYAN" => "CHALIYAN",
            "CHALLIYA" => "CHALLIYA",
            "CHALVADI" => "CHALVADI",
            "CHAMAR" => "CHAMAR",
            "CHAMBHAR" => "CHAMBHAR",
            "CHAMBOTI" => "CHAMBOTI",
            "CHAMBUKUTTI" => "CHAMBUKUTTI",
            "CHAMGAR" => "CHAMGAR",
            "CHAMMADIA" => "CHAMMADIA",
            "CHANDALA" => "CHANDALA",
            "CHANNAYYA" => "CHANNAYYA",
            "CHAPPER BAND (MUSLIM)" => "CHAPPER BAND (MUSLIM)",
            "CHAPPER BANDA" => "CHAPPER BANDA",
            "CHAPTEGAR" => "CHAPTEGAR",
            "CHARA" => "CHARA",
            "CHARODI" => "CHARODI",
            "CHATTADA SRIVAISHNAVA" => "CHATTADA SRIVAISHNAVA",
            "CHATTADA VAISHNAVA" => "CHATTADA VAISHNAVA",
            "CHENCHU" => "CHENCHU",
            "CHENCHWAR" => "CHENCHWAR",
            "CHENNA DASAR" => "CHENNA DASAR",
            "CHHAR" => "CHHAR",
            "CHHARA" => "CHHARA",
            "CHHETRI" => "CHHETRI",
            "CHIGARI BETAGAR" => "CHIGARI BETAGAR",
            "CHIPPI" => "CHIPPI",
            "CHIPPIGA" => "CHIPPIGA",
            "CHITARA" => "CHITARA",
            "CHITRAGAR" => "CHITRAGAR",
            "CHITRAKATHIJOSHI" => "CHITRAKATHIJOSHI",
            "CHODHARA" => "CHODHARA",
            "CHOURIYA" => "CHOURIYA",
            "CHRISTIAN" => "CHRISTIAN",
            "CHUNAR" => "CHUNAR",
            "CHUNCHAR" => "CHUNCHAR",
            "DAALIJA" => "DAALIJA",
            "DAALJI" => "DAALJI",
            "DAAVAT" => "DAAVAT",
            "DAIVAGNYA BRAHMIN" => "DAIVAGNYA BRAHMIN",
            "DAKKAL" => "DAKKAL",
            "DAKKALIGA" => "DAKKALIGA",
            "DANG-DASA" => "DANG-DASA",
            "DARJI" => "DARJI",
            "DARVESU" => "DARVESU",
            "DAS VOKKALIGA" => "DAS VOKKALIGA",
            "DASA BANAJIGA" => "DASA BANAJIGA",
            "DASARA BALAJIGA" => "DASARA BALAJIGA",
            "DASARA BALIJA" => "DASARA BALIJA",   
            "DASARA BANAJIGA" => "DASARA BANAJIGA",
            "DASARI" => "DASARI",
            "DASARU" => "DASARU",
            "DAURIGOSAYI" => "DAURIGOSAYI",
            "DAVARI" => "DAVARI",
            "DAVERI" => "DAVERI",
            "DEEVAR" => "DEEVAR",
            "DERIA" => "DERIA",
            "DESHA BHANDARI" => "DESHA BHANDARI",                                                                                     
            "DEVADASI" => "DEVADASI",
            "DEVADIGA" => "DEVADIGA",
            "DEVALI" => "DEVALI",
            "DEVANG" => "DEVANG",
            "DEVANGA" => "DEVANGA",
            "DEVAR" => "DEVAR",
            "DEVARAMAKKALU" => "DEVARAMAKKALU",
            "DEVARI" => "DEVARI",
            "DHANAGAR" => "DHANAGAR",
            "DHARMARAJA KAPU" => "DHARMARAJA KAPU",
            "DHED" => "DHED",
            "DHEGU MEGU" => "DHEGU MEGU",
            "DHOBI" => "DHOBI",
            "DHOLI" => "DHOLI",
            "DHOLI BHIL" => "DHOLI BHIL",
            "DHOR " => "DHOR",
            "DHOR KATHODI" => "DHOR KATHODI",
            "DHOR KATKARI" => "DHOR KATKARI",
            "DIGWAN" => "DIGWAN",
            "DIVARA MAKKALU" => "DIVARA MAKKALU",
            "DOGRA" => "DOGRA",
            "DOKKALWAR" => "DOKKALWAR",
            "DOM" => "DOM",
            "DOMBARA" => "DOMBARA",
            "DOMBI-DASARU" => "DOMBI-DASARU",
            "DUBLA" => "DUBLA",
            "DUDEKULA" => "DUDEKULA",
            "DUNGRI BHIL" => "DUNGRI BHIL",
            "DUNGRI GARASIA" => "DUNGRI GARASIA",
            "DURGAMURGA" => "DURGAMURGA",
            "EDIGA" => "EDIGA",
            "EGALIKA" => "EGALIKA",
            "ELIGA" => "ELIGA",
            "ELLAMALWAR" => "ELLAMALWAR",
            "ERAKALA" => "ERAKALA",
            "EZHAVA" => "EZHAVA",
            "FULL MALI" => "FULL MALI",
            "GAABIT" => "GAABIT",
            "GABBIT" => "GABBIT",
            "GABIT" => "GABIT",
            "GADIGA" => "GADIGA",
            "GALADAKONKANI" => "GALADAKONKANI",
            "GAM GAWADA" => "GAM GAWADA",
            "GAM GAWDA" => "GAM GAWDA",
            "GAMALLA" => "GAMALLA",
            "GAMIT" => "GAMIT",
            "GAMTA" => "GAMTA",
            "GAMVOKKAL" => "GAMVOKKAL",
            "GANAGI" => "GANAGI",
            "GANDLA" => "GANDLA",
            "GANGADKAR VOKKALIGA" => "GANGADKAR VOKKALIGA",
            "GANGAKULA" => "GANGAKULA",
            "GANGAMATHA" => "GANGAMATHA",
            "GANGAMATHASTHA" => "GANGAMATHASTHA",
            "GANGAPUTRA" => "GANGAPUTRA",
            "GANGEMAKKALU" => "GANGEMAKKALU",
            "GANIGA" => "GANIGA",
            "GANIKA" => "GANIKA",
            "GANTI CHORES" => "GANTI CHORES",
            "GAPIT" => "GAPIT",
            "GARADI" => "GARADI",
            "GARADIGA" => "GARADIGA",
            "GARODA" => "GARODA",
            "GARUDI" => "GARUDI",
            "GARUDIGA" => "GARUDIGA",
            "GATTI" => "GATTI",
            "GATTIYAVARU" => "GATTIYAVARU",
            "GAULI" => "GAULI",
            "GAURIGA" => "GAURIGA",
            "GAVADA" => "GAVADA",
            "GAVADI" => "GAVADI",
            "GAVALI" => "GAVALI",
            "GAVANDI" => "GAVANDI",
            "GAVIT" => "GAVIT",
            "GAVLI" => "GAVLI",
            "GEJJIGARA" => "GEJJIGARA",
            "GHADI" => "GHADI",
            "GHADSHI" => "GHADSHI",
            "GHADSI" => "GHADSI",
            "GHISADE" => "GHISADE",
            "GHISADI" => "GHISADI",
            "GHONDALI" => "GHONDALI",
            "GIDDIDKI" => "GIDDIDKI",
            "GIRINI WADDAR" => "GIRINI WADDAR",
            "GODDA" => "GODDA",
            "GOLLA" => "GOLLA",
            "GOND" => "GOND",
            "GONDALI" => "GONDALI",
            "GONDALIGA" => "GONDALIGA",
            "GONDHALI" => "GONDHALI",
            "GONDHALLI" => "GONDHALLI",
            "GONI CHETTY" => "GONI CHETTY",
            "GONIGA MANE" => "GONIGA MANE",
            "GOONDLA" => "GOONDLA",
            "GOPALA" => "GOPALA",
            "GOPALI" => "GOPALI",
            "GORAYA" => "GORAYA",
            "GORE OR GORIA" => "GORE OR GORIA",
            "GOSAIN" => "GOSAIN",
            "GOSANGI" => "GOSANGI",
            "GOSAVI" => "GOSAVI",
            "GOSAYI" => "GOSAYI",
            "GOUDA  " => "GOUDA",
            "GOULI" => "GOULI",
            "GOUNDI" => "GOUNDI",
            "GOUNDLA" => "GOUNDLA",
            "GOURIGA" => "GOURIGA",
            "GOVANDI" => "GOVANDI",
            "GOWDA" => "GOWDA",
            "GOWDALU" => "GOWDALU",
            "GOWLI" => "GOWLI",
            "GOWNDER" => "GOWNDER",
            "GOWRI" => "GOWRI",
            "GOWRIGA" => "GOWRIGA",
            "GOWRIMARATHA" => "GOWRIMARATHA",
            "GOWRIMATHA" => "GOWRIMATHA",
            "GRAM VAKKAL" => "GRAM VAKKAL",
            "GRAMA VOKKALU" => "GRAMA VOKKALU",
            "GSB" => "GSB",
            "GUDIGARA" => "GUDIGARA",
            "GUJAR" => "GUJAR",
            "GULLI" => "GULLI",
            "GUNAGA" => "GUNAGA",
            "GUNAGI" => "GUNAGI",
            "GUNDE BESTHA" => "GUNDE BESTHA",
            "GURAV" => "GURAV",
            "GURAVA" => "GURAVA",
            "GURKHA" => "GURKHA",
            "GUROU" => "GUROU",
            "GUSAI" => "GUSAI",
            "GUZAR" => "GUZAR",
            "HADAPADA " => "HADAPADA",
            "HAJAMA" => "HAJAMA",
            "HAKKIPIKKI" => "HAKKIPIKKI",
            "HALA KSHATRIYA" => "HALA KSHATRIYA",
            "HALAKKI VOKKALU" => "HALAKKI VOKKALU",
            "HALALKHOR" => "HALALKHOR",
            "HALAWAKKI VAKKAL" => "HALAWAKKI VAKKAL",
            "HALAWAKKI WAKKAL" => "HALAWAKKI WAKKAL",
            "HALE PAIK" => "HALE PAIK",
            "HALEER" => "HALEER",
            "HALEPAIKARU" => "HALEPAIKARU",
            "HALLIKAR" => "HALLIKAR",
            "HALLIKAR VOKKALIGA" => "HALLIKAR VOKKALIGA",   
            "HALPATI" => "HALPATI",
            "HALSAR" => "HALSAR",
            "HALUMATHA" => "HALUMATHA",
            "HANABAR" => "HANABAR",
            "HANDERVUT" => "HANDERVUT",
            "HANDEVAZIR" => "HANDEVAZIR",
            "HANDI JOGIS" => "HANDI JOGIS",
            "HARAKANTHRA" => "HARAKANTHRA",
            "HARALAYYA" => "HARALAYYA",
            "HARALI" => "HARALI",
            "HARANSHIKARI" => "HARANSHIKARI",
            "HARANSHIKARI (2003)" => "HARANSHIKARI (2003)",
            "HARIKANTHRA" => "HARIKANTHRA",
            "HASALARU" => "HASALARU",
            "HASLA" => "HASLA",
            "HATAGAR" => "HATAGAR",
            "HAWADIGA" => "HAWADIGA",
            "HAWGAR" => "HAWGAR",
            "HEGGADE" => "HEGGADE",
            "HELAVA" => "HELAVA",
            "HELOVA" => "HELOVA",
            "HINDU SADRU" => "HINDU SADRU",
            "HIRSHIKARI" => "HIRSHIKARI",
            "HOLAR" => "HOLAR",
            "HOLAYA" => "HOLAYA",
            "HOLAYA DASAR" => "HOLAYA DASAR",
            "HOLER" => "HOLER",
            "HOLEVA" => "HOLEVA",
            "HOLEYA" => "HOLEYA",
            "HOLEYA DASARI" => "HOLEYA DASARI",
            "HONNIYAR" => "HONNIYAR",
            "HOOGAR" => "HOOGAR",
            "HOOVADIGA" => "HOOVADIGA",
            "HOWGAR" => "HOWGAR",
            "HUGAR" => "HUGAR",
            "HULKAR" => "HULKAR",
            "HUTGAR " => "HUTGAR",
            "HUTKAR" => "HUTKAR",
            "IDIGA" => "IDIGA",
            "IIIAVAN" => "IIIAVAN",
            "IIIGA" => "IIIGA",
            "IRULAR" => "IRULAR",
            "IRULIGA" => "IRULIGA",
            "JAAT" => "JAAT",
            "JADAR" => "JADAR",
            "JAGGALI" => "JAGGALI",
            "JAINS (DIGAMBARAS)" => "JAINS (DIGAMBARAS)",
            "JALAGARA" => "JALAGARA",
            "JAM KHANA" => "JAM KHANA",
            "JAMBUVULU" => "JAMBUVULU",
            "JANAPPAN" => "JANAPPAN",
            "JANDRA" => "JANDRA",
            "JANGALA" => "JANGALA",
            "JATTI" => "JATTI",
            "JAVERI" => "JAVERI",
            "JAWARI" => "JAWARI",
            "JED" => "JED",
            "JEER" => "JEER",
            "JEERAGARA" => "JEERAGARA",
            "JENU KURUBA" => "JENU KURUBA",
            "JETTI " => "JETTI",
            "JINGAR" => "JINGAR",
            "JOGAR" => "JOGAR",
            "JOGER" => "JOGER",
            "JOGI" => "JOGI",
            "JOGTIN" => "JOGTIN",
            "JOHARI" => "JOHARI",
            "JOSHI" => "JOSHI",
            "JULOHI" => "JULOHI",
            "JYOTHI NAGARA  " => "JYOTHI NAGARA",
            "KABBALIGA" => "KABBALIGA",
            "KABBER" => "KABBER",
            "KABBERA" => "KABBERA",
            "KABBILI" => "KABBILI",
            "KADAIYAN" => "KADAIYAN",
            "KADRI VAISHNAVA" => "KADRI VAISHNAVA",
            "KADU KONKANI" => "KADU KONKANI",
            "KADU KURUBA" => "KADU KURUBA",
            "KAHAR" => "KAHAR",
            "KAIKADI" => "KAIKADI",
            "KAIKOLAN " => "KAIKOLAN", 
            "KAKKAYYA" => "KAKKAYYA",
            "KALAL" => "KALAL",
            "KALAL KHATIK" => "KALAL KHATIK",
            "KALARI" => "KALARI",
            "KALAVANT" => "KALAVANT",
            "KALAVANTHI" => "KALAVANTHI",
            "KALAYIRI" => "KALAYIRI",
            "KALKARI , KELKARI" => "KALKARI , KELKARI",
            "KALLADI" => "KALLADI",
            "KALLAR" => "KALLAR",
            "KALLU KUTIGA UPPARA" => "KALLU KUTIGA UPPARA",
            "KALLU VADDAR" => "KALLU VADDAR",
            "KAMAN" => "KAMAN",
            "KAMASAL" => "KAMASAL",
            "KAMATI MOCHI" => "KAMATI MOCHI",
            "KAMATTI" => "KAMATTI",
            "KAMBAR" => "KAMBAR",
            "KAMMA" => "KAMMA",
            "KAMMALAN" => "KAMMALAN",
            "KAMMARA " => "KAMMARA",
            "KAMSALA" => "KAMSALA",
            "KAMSAN" => "KAMSAN",
            "KANAKAN" => "KANAKAN",
            "KANAKAR" => "KANAKAR",
            "KANBI" => "KANBI",
            "KANCHAGAR" => "KANCHAGAR",
            "KANCHORA" => "KANCHORA",
            "KANCHORI" => "KANCHORI",
            "KANCHUGARA" => "KANCHUGARA",
            "KANISAN" => "KANISAN",
            "KANIYA" => "KANIYA",
            "KANIYAN " => "KANIYAN",
            "KANIYAR" => "KANIYAR",
            "KANIYARU" => "KANIYARU",
            "KANJAR" => "KANJAR",
            "KANJARI" => "KANJARI",
            "KANJIR" => "KANJIR",
            "KANJIRBHAT" => "KANJIRBHAT",
            "KANKAYYA" => "KANKAYYA",
            "KANSAR" => "KANSAR",
            "KANYAN" => "KANYAN",
            "KAPADIA NAYAKA" => "KAPADIA NAYAKA",
            "KAPALI" => "KAPALI",
            "KAPU" => "KAPU",
            "KARAKARMUNDA" => "KARAKARMUNDA",
            "KARE VOKKALU" => "KARE VOKKALU",
            "KARIKUDUMBI" => "KARIKUDUMBI",
            "KARUNIKA" => "KARUNIKA",
            "KARUVA" => "KARUVA",
            "KASAB" => "KASAB",
            "KASAI" => "KASAI",
            "KASAR" => "KASAR",
            "KASBAN" => "KASBAN",
            "KASBIN" => "KASBIN",
            "KASHIKAPADI" => "KASHIKAPADI",
            "KASHIKAPDI" => "KASHIKAPDI",
            "KATABAR" => "KATABAR",
            "KATABU" => "KATABU",
            "KATHODI" => "KATHODI",
            "KATIK" => "KATIK",
            "KATKARI" => "KATKARI",
            "KATTUNAYAKAN" => "KATTUNAYAKAN",
            "KATUGA" => "KATUGA",
            "KATUKA" => "KATUKA",
            "KAVADI" => "KAVADI",
            "KAVUTIAN" => "KAVUTIAN",
            "KELASI" => "KELASI",
            "KEPMARIS" => "KEPMARIS",
            "KHALPA" => "KHALPA",
            "KHANJAR BHAT" => "KHANJAR BHAT",
            "KHARIA" => "KHARIA",
            "KHARVI" => "KHARVI",
            "KHATIK" => "KHATIK",
            "KHELKARI" => "KHELKARI",
            "KHUMARA" => "KHUMARA",
            "KHUMBAR" => "KHUMBAR",
            "KICHAGARA" => "KICHAGARA",
            "KILLIKYATA" => "KILLIKYATA",
            "KODAGARU" => "KODAGARU",
            "KODAGU HEGGADE " => "KODAGU HEGGADE",
            "KODAGU KAPALA" => "KODAGU KAPALA",
            "KOKNA" => "KOKNA",
            "KOKNI" => "KOKNI",
            "KOLARI" => "KOLARI",
            "KOLAYAN" => "KOLAYAN",
            "KOLAYIRI" => "KOLAYIRI",
            "KOLCHA" => "KOLCHA",
            "KOLERI" => "KOLERI",
            "KOLGHA" => "KOLGHA",
            "KOLHATI" => "KOLHATI",
            "KOLHATIGI" => "KOLHATIGI",
            "KOLI" => "KOLI",
            "KOLI DHOR" => "KOLI DHOR",
            "KOLIMAHADEV" => "KOLIMAHADEV",
            "KOLLA" => "KOLLA",
            "KOLLALA" => "KOLLALA",
            "KOLUPULVANDLU" => "KOLUPULVANDLU",
            "KOLYIRI" => "KOLYIRI",
            "KOMARPAIK KSHATRIYA " => "KOMARPAIK KSHATRIYA",
            "KOMARPANT " => "KOMARPANT",
            "KONAR" => "KONAR",
            "KONDA KAPUS" => "KONDA KAPUS",
            "KONKAN KHARVI" => "KONKAN KHARVI",
            "KONKAN MARATHA" => "KONKAN MARATHA",
            "KONKANI ACHAR" => "KONKANI ACHAR",
            "KONNUR" => "KONNUR",
            "KOOSA" => "KOOSA",
            "KORACHA  " => "KORACHA",
            "KORAGA" => "KORAGA",
            "KORAGAR" => "KORAGAR",
            "KORAMA " => "KORAMA",
            "KORAR" => "KORAR",
            "KORMASETTY" => "KORMASETTY",
            "KORWARI" => "KORWARI",
            "KOSHTI" => "KOSHTI",
            "KOTA" => "KOTA",
            "KOTARI" => "KOTARI",
            "KOTARY" => "KOTARY",
            "KOTE KSHATRIYA" => "KOTE KSHATRIYA",
            "KOTEGAR" => "KOTEGAR",
            "KOTEGARA" => "KOTEGARA",
            "KOTEYAR" => "KOTEYAR",
            "KOTHATI" => "KOTHATI",
            "KOTTARI" => "KOTTARI",
            "KOTTARY" => "KOTTARY",
            "KOTTEGARA" => "KOTTEGARA",
            "KOTTEYARA" => "KOTTEYARA",
            "KOTWALIA" => "KOTWALIA",
            "KOYA " => "KOYA",
            "KOYAVA" => "KOYAVA",
            "KRISHNA GAVALI" => "KRISHNA GAVALI",
            "KRISHNA GOLLA" => "KRISHNA GOLLA",
            "KSHATRI" => "KSHATRI",
            "KSHATRIYA " => "KSHATRIYA",
            "KSHATRIYA LAD" => "KSHATRIYA LAD",
            "KSHATRIYA MARATHA" => "KSHATRIYA MARATHA",
            "KSHAURIKA" => "KSHAURIKA",
            "KSHOWRAD" => "KSHOWRAD",
            "KSHOWRIK" => "KSHOWRIK",
            "KSHOWRIKA" => "KSHOWRIKA",
            "KUDIYA " => "KUDIYA",
            "KUDUBI" => "KUDUBI",
            "KUDUMBAN" => "KUDUMBAN",
            "KUKNA" => "KUKNA",
            "KULA" => "KULA",
            "KULALA" => "KULALA",
            "KULALAR" => "KULALAR",
            "KULAVAD" => "KULAVAD",
            "KULAWADI MARATI" => "KULAWADI MARATI",
            "KULWADI" => "KULWADI",
            "KUMARA KSHATRIYA" => "KUMARA KSHATRIYA",
            "KUMARA PANTH  " => "KUMARA PANTH",
            "KUMBAR" => "KUMBAR",
            "KUMBARA" => "KUMBARA",
            "KUMBARD" => "KUMBARD",
            "KUMBHAR" => "KUMBHAR",
            "KUMBRI MARATI " => "KUMBRI MARATI",
            "KUMMARA" => "KUMMARA",
            "KUNBI" => "KUNBI",
            "KUNCHAVAKKAL" => "KUNCHAVAKKAL",
            "KUNCHI" => "KUNCHI",
            "KUNCHITIGA" => "KUNCHITIGA",
            "KURAB" => "KURAB",
            "KURAVAN" => "KURAVAN",
            "KURMA" => "KURMA",
            "KURMI" => "KURMI",
            "KURNI" => "KURNI",
            "KUROVAN" => "KUROVAN",
            "KURUB" => "KURUB",
            "KURUBA  " => "KURUBA",
            "KURUBAN" => "KURUBAN",
            "KURUHINA SETTY" => "KURUHINA SETTY",
            "KURUMANS" => "KURUMANS",
            "KURUMBA" => "KURUMBA",
            "KURUMBAN" => "KURUMBAN",
            "KUSAVAN" => "KUSAVAN",
            "KUTUMA" => "KUTUMA",
            "LAD" => "LAD",
            "LADAF" => "LADAF",
            "LADAR" => "LADAR",
            "LADARA" => "LADARA",
            "LADARU " => "LADARU",
            "LALBEGI" => "LALBEGI",
            "LAMANI" => "LAMANI",
            "LAMBADA" => "LAMBADA",
            "LAMBADI" => "LAMBADI",
            "LAMBAID" => "LAMBAID",
            "LAMBANI" => "LAMBANI",
            "LINGADER" => "LINGADER",
            "LINGAYATH" => "LINGAYATH",
            "LONARI" => "LONARI",
            "LUHAR" => "LUHAR",
            "MAALGAR" => "MAALGAR",
            "MACHALA" => "MACHALA",
            "MACHIGOR" => "MACHIGOR",
            "MADARI" => "MADARI",
            "MADDAR" => "MADDAR",
            "MADIG" => "MADIG",
            "MADIGA" => "MADIGA",
            "MADIVALA" => "MADIVALA",
            "MAHA MALASAR" => "MAHA MALASAR",
            "MAHALE" => "MAHALE",
            "MAHAR" => "MAHAR",
            "MAHYAVANSHI " => "MAHYAVANSHI",
            "MAILA" => "MAILA",
            "MALA" => "MALA",
            "MALA DASARI" => "MALA DASARI",
            "MALA HANNAI" => "MALA HANNAI",
            "MALA JANGAM" => "MALA JANGAM",
            "MALA MASTI" => "MALA MASTI",
            "MALA SALE" => "MALA SALE",
            "MALA SANYASI" => "MALA SANYASI",
            "MALAIKUDI" => "MALAIKUDI",
            "MALASAR" => "MALASAR",
            "MALAWA" => "MALAWA",
            "MALAYA" => "MALAYA",
            "MALAYALI BILLAVA" => "MALAYALI BILLAVA",
            "MALAYEKANDI" => "MALAYEKANDI",
            "MALERU" => "MALERU",
            "MALEYA" => "MALEYA",
            "MALI" => "MALI",
            "MALKANA" => "MALKANA",
            "MALLARU MALLA KSHATRIYA" => "MALLARU MALLA KSHATRIYA",
            "MANG" => "MANG",
            "MANG GARODI" => "MANG GARODI",
            "MANG GARUDI" => "MANG GARUDI",
            "MANGALA" => "MANGALA",
            "MANIYANI" => "MANIYANI",
            "MANNAN" => "MANNAN",
            "MANNE" => "MANNE",
            "MANNU VODDAR" => "MANNU VODDAR",
            "MANSOORI" => "MANSOORI",
            "MANSURI" => "MANSURI",
            "MARASU VOKKALIGA" => "MARASU VOKKALIGA",
            "MARATHA " => "MARATHA",
            "MARATI  " => "MARATI",
            "MARATTI" => "MARATTI",
            "MARAVAN" => "MARAVAN",
            "MARAVAR" => "MARAVAR",
            "MARAYAN" => "MARAYAN",
            "MARTA" => "MARTA",
            "MARU VANKAR" => "MARU VANKAR",
            "MASANIA YOGI" => "MASANIA YOGI",
            "MASTHI" => "MASTHI",
            "MATANG," => "MATANG,",
            "MAVCHI" => "MAVCHI",
            "MEDA  " => "MEDA",
            "MEDARA" => "MEDARA",
            "MEDARI" => "MEDARI",
            "MEENAGAR" => "MEENAGAR",
            "MEHTAR" => "MEHTAR",
            "MELAGARA" => "MELAGARA",
            "MELU SAKKREYAVARU" => "MELU SAKKREYAVARU",
            "MELUSAKKARE" => "MELUSAKKARE",
            "MESTA" => "MESTA",
            "MESTHA" => "MESTHA",
            "METRI" => "METRI",
            "MEWASI BHIL" => "MEWASI BHIL",
            "MINIMADIG" => "MINIMADIG",
            "MIRAL" => "MIRAL",
            "MOCHI" => "MOCHI",
            "MOCHIGAR" => "MOCHIGAR",
            "MODIGA" => "MODIGA",
            "MODIKAR" => "MODIKAR",
            "MODIKARA" => "MODIKARA",
            "MOGAVEERA" => "MOGAVEERA",
            "MOGER" => "MOGER",
            "MOOLYA" => "MOOLYA",
            "MOTA NAYAKA" => "MOTA NAYAKA",
            "MOYILI" => "MOYILI",
            "MUCHI" => "MUCHI",
            "MUDHAR" => "MUDHAR",
            "MUKKAVAN" => "MUKKAVAN",
            "MUNNAR" => "MUNNAR",
            "MUNNUR" => "MUNNUR",
            "MUNNUR KAPU" => "MUNNUR KAPU",
            "MURRARI" => "MURRARI",
            "MUSHTIGA" => "MUSHTIGA",
            "MUSLIM" => "MUSLIM",
            "MUTRACHA" => "MUTRACHA",
            "MUTRASI" => "MUTRASI",
            "MYASA NAYAKA" => "MYASA NAYAKA",
            "NADAF" => "NADAF",
            "NADAR" => "NADAR",
            "NADAVA" => "NADAVA",
            "NADAVAR" => "NADAVAR",
            "NADIG" => "NADIG",
            "NADIGA" => "NADIGA",
            "NADOR" => "NADOR",
            "NADORA" => "NADORA",
            "NAIDU" => "NAIDU",
            "NAIK" => "NAIK",
            "NAIKAMAKKALU" => "NAIKAMAKKALU",
            "NAIKDA  " => "NAIKDA",
            "NAIKPOD" => "NAIKPOD",
            "NAIKWADI" => "NAIKWADI",
            "NAIR" => "NAIR",
            "NAIRI " => "NAIRI",
            "NAIRY" => "NAIRY",
            "NAJABUND" => "NAJABUND",
            "NALABUND" => "NALABUND",
            "NALKI" => "NALKI",
            "NAMADA UPPARA" => "NAMADA UPPARA",
            "NAMADHARI" => "NAMADHARI",
            "NAMADHARI GOWDA" => "NAMADHARI GOWDA",
            "NAMDEV" => "NAMDEV",
            "NAMDEV SIMPI" => "NAMDEV SIMPI",
            "NAMDHARI VOKKALIGA" => "NAMDHARI VOKKALIGA",
            "NANA NAYAKA" => "NANA NAYAKA",
            "NANDIWALA" => "NANDIWALA",
            "NAPITHA" => "NAPITHA",
            "NAT" => "NAT",
            "NATHA PANTHI" => "NATHA PANTHI",
            "NATUVA" => "NATUVA",
            "NAVALIG" => "NAVALIG",
            "NAVI" => "NAVI",
            "NAYAK" => "NAYAK",
            "NAYAKA" => "NAYAKA",
            "NAYANAJA KSHATRI" => "NAYANAJA KSHATRI",
            "NAYANAJA KSHATRIYA" => "NAYANAJA KSHATRIYA",
            "NAYINDA" => "NAYINDA",
            "NEELAGAR" => "NEELAGAR",
            "NEIKAR" => "NEIKAR",
            "NETKANI" => "NETKANI",
            "NEYGI" => "NEYGI",
            "NGMADHARI" => "NGMADHARI",
            "NHAVI" => "NHAVI",
            "NILARI" => "NILARI",
            "NIRSHIKARI" => "NIRSHIKARI",
            "OLGANA" => "OLGANA",
            "OSTHAN" => "OSTHAN",
            "OTARI" => "OTARI",
            "OTHERS" => "OTHERS",
            "PADIAR" => "PADIAR",
            "PADIT " => "PADIT",
            "PADITHI" => "PADITHI",
            "PADMA SALE " => "PADMA SALE",
            "PADMA SHALI" => "PADMA SHALI",
            "PADTI" => "PADTI",
            "PADVI" => "PADVI",
            "PAGI" => "PAGI",
            "PAIDI" => "PAIDI",
            "PAKANATHI JANGAMA" => "PAKANATHI JANGAMA",
            "PALEGAR" => "PALEGAR",
            "PALLI" => "PALLI",
            "PALLIYAN" => "PALLIYAN",
            "PAMLOR" => "PAMLOR",
            "PANABA" => "PANABA",
            "PANASA" => "PANASA",
            "PANCHAL" => "PANCHAL",
            "PANDAR" => "PANDAR",
            "PANDARA" => "PANDARA",
            "PANDARAM" => "PANDARAM",
            "PANGUAL" => "PANGUAL",
            "PANGUSAL" => "PANGUSAL",
            "PANIKA" => "PANIKA",
            "PANIYAN" => "PANIYAN",
            "PANNEKARA KONKANI" => "PANNEKARA KONKANI",
            "PANO" => "PANO",
            "PANSA" => "PANSA",
            "PARADESHI-BHAMPT" => "PARADESHI-BHAMPT",
            "PARADHIS" => "PARADHIS",
            "PARDHI " => "PARDHI",
            "PARIT" => "PARIT",
            "PARIVARA" => "PARIVARA",
            "PARIVARA BANT" => "PARIVARA BANT",
            "PARIVARA NAYAKA" => "PARIVARA NAYAKA",
            "PARIYALA  " => "PARIYALA",
            "PATELIA" => "PATELIA",
            "PATRA" => "PATRA",
            "PATRAMELA" => "PATRAMELA",
            "PATTA SALE" => "PATTA SALE",
            "PATTAR" => "PATTAR",
            "PATTASALI" => "PATTASALI",
            "PATTEGAR" => "PATTEGAR",
            "PATVEKARI" => "PATVEKARI",
            "PAWRA" => "PAWRA",
            "PHANSE PARDHI" => "PHANSE PARDHI",
            "PHASACHARI" => "PHASACHARI",
            "PHOOL MALI" => "PHOOL MALI",
            "PHOOLARI" => "PHOOLARI",
            "PHUL MALI" => "PHUL MALI",
            "PHULARI" => "PHULARI",
            "PICHATI" => "PICHATI",
            "PICHGUNTALA" => "PICHGUNTALA",
            "PICHIGUNTA" => "PICHIGUNTA",
            "PICHIGUNTALA" => "PICHIGUNTALA",
            "PINGALE" => "PINGALE",
            "PINGLE" => "PINGLE",
            "PINJARA" => "PINJARA",
            "PINJARI" => "PINJARI",
            "POLADAVARU" => "POLADAVARU",
            "POLEDAVA " => "POLEDAVA",
            "POOJARI" => "POOJARI",
            "PULLAVAN" => "PULLAVAN",
            "RACHEVAR" => "RACHEVAR",
            "RAJABHOI" => "RAJABHOI",
            "RAJAKA" => "RAJAKA",
            "RAJAPURI" => "RAJAPURI",
            "RAJAPUT" => "RAJAPUT",
            "RAJAVAR " => "RAJAVAR",
            "RAJGOND" => "RAJGOND",
            "RAJKOYA" => "RAJKOYA",
            "RAJPUR" => "RAJPUR",
            "RAJU KSHATRIYA" => "RAJU KSHATRIYA",
            "RAJU-RAJU" => "RAJU-RAJU",
            "RAJUWAR " => "RAJUWAR",
            "RAMA KSHATRIYA" => "RAMA KSHATRIYA",
            "RAMA RAJ KSHATRIYA" => "RAMA RAJ KSHATRIYA",
            "RANGARE" => "RANGARE",
            "RANGARI" => "RANGARI",
            "RANGREZ" => "RANGREZ",
            "RANIGAR" => "RANIGAR",
            "RATHAWA" => "RATHAWA",
            "RAVAL" => "RAVAL",
            "RAVALIA" => "RAVALIA",
            "RAVAT" => "RAVAT",
            "RAWAL BHIL" => "RAWAL BHIL",
            "RAYA RAWATH" => "RAYA RAWATH",
            "REDDY " => "REDDY",
            "REDDY (BALIJA)" => "REDDY (BALIJA)",
            "REDDY VOKKALIGA" => "REDDY VOKKALIGA",
            "REINUDAS" => "REINUDAS",
            "REMOSHI" => "REMOSHI",
            "ROHIDAS" => "ROHIDAS",
            "ROHIT" => "ROHIT",
            "RUKHI" => "RUKHI",
            "SAALE " => "SAALE",
            "SADAJOSHI" => "SADAJOSHI",
            "SADAR" => "SADAR",
            "SADARA GOWDA" => "SADARA GOWDA",
            "SADARA/ SADARI" => "SADARA/ SADARI",
            "SADARU" => "SADARU",
            "SADKULA" => "SADKULA",
            "SADU GOWDA" => "SADU GOWDA",
            "SADU GOWDAR" => "SADU GOWDAR",
            "SADUMATA" => "SADUMATA",
            "SADUSETTY" => "SADUSETTY",
            "SAGARA" => "SAGARA",
            "SAI" => "SAI",
            "SAJJAN KUMBARA" => "SAJJAN KUMBARA",
            "SAKAJAVADU" => "SAKAJAVADU",
            "SAKALA" => "SAKALA",
            "SALAPARU" => "SALAPARU",
            "SALE " => "SALE" ,
            "SAMAGAR" => "SAMAGAR",
            "SAMERAYA" => "SAMERAYA",
            "SANIYAAR" => "SANIYAAR",
            "SANJOGI" => "SANJOGI",
            "SANSIA" => "SANSIA",
            "SANYASI" => "SANYASI",
            "SARANTA" => "SARANTA",
            "SARODA" => "SARODA",
            "SARORDI" => "SARORDI",
            "SARPA VOKKALIGA" => "SARPA VOKKALIGA",
            "SATANI" => "SATANI",
            "SATARKAR" => "SATARKAR",
            "SATTADA SRIVAISHNA" => "SATTADA SRIVAISHNA",
            "SATTADA VAISHNAVA" => "SATTADA VAISHNAVA",
            "SATTADAVAL" => "SATTADAVAL",
            "SATTADAVAN" => "SATTADAVAN",
            "SAVITHA" => "SAVITHA",
            "SENGUNDHAR" => "SENGUNDHAR",
            "SEREGARA" => "SEREGARA",
            "SERUGARA  " => "SERUGARA",
            "SERVEGAR" => "SERVEGAR",
            "SERVGAR  " => "SERVGAR",
            "SETTY BALIJA " => "SETTY BALIJA",
            "SETTY BANAJIGA" => "SETTY BANAJIGA",
            "SHAMBHUKULA KSHATRIYA" => "SHAMBHUKULA KSHATRIYA",
            "SHANAN" => "SHANAN",
            "SHEREGAR" => "SHEREGAR",
            "SHIKALGAR" => "SHIKALGAR",
            "SHIKKALIGAR" => "SHIKKALIGAR",
            "SHILWAKKAL" => "SHILWAKKAL",
            "SHIMPI" => "SHIMPI",
            "SHOLAGA" => "SHOLAGA",
            "SIDDI  " => "SIDDI",
            "SIKKALIGARA" => "SIKKALIGARA",
            "SILLEKYATHAS" => "SILLEKYATHAS",
            "SILPI" => "SILPI",
            "SIMPI" => "SIMPI",
            "SIVIYAR" => "SIVIYAR",
            "SOHAGAR" => "SOHAGAR",
            "SOLIGARU" => "SOLIGARU",
            "SOMAVAMSHA ARYA KSHATRIYA" => "SOMAVAMSHA ARYA KSHATRIYA",
            "SOMAVAMSHA KSHATRIYA" => "SOMAVAMSHA KSHATRIYA",
            "SOMAVAMSHA SAHASRARJUNA KSHATRIYA" => "SOMAVAMSHA SAHASRARJUNA KSHATRIYA",
            "SON KATHODI" => "SON KATHODI",
            "SON KATKARI" => "SON KATKARI",
            "SONAR" => "SONAR",
            "SONIGA" => "SONIGA",
            "SONY" => "SONY",
            "ST" => "ST",
            "STANIKA" => "STANIKA",
            "STGH" => "STGH",
            "SUDIR" => "SUDIR",
            "SUDRA" => "SUDRA",
            "SUGALI" => "SUGALI",
            "SUGANDHI LAD" => "SUGANDHI LAD",
            "SUKALI" => "SUKALI",
            "SUNAGARA" => "SUNAGARA",
            "SUNNA UPPARA" => "SUNNA UPPARA",
            "SUNNAGARA" => "SUNNAGARA",
            "SUPLIG" => "SUPLIG",
            "SURYAVAMSHA KSHATRIYA" => "SURYAVAMSHA KSHATRIYA",
            "SUTAR" => "SUTAR",
            "SUTSALI" => "SUTSALI",
            "SWAKULA SALE" => "SWAKULA SALE",
            "SWAKULA SALI " => "SWAKULA SALI",
            "TACEHAN" => "TACEHAN",
            "TACHAYIRI" => "TACHAYIRI",
            "TADVI BHIL" => "TADVI BHIL",
            "TAKANKAR" => "TAKANKAR",
            "TAKARI" => "TAKARI",
            "TALAVIA" => "TALAVIA",
            "TALAWARA" => "TALAWARA",
            "TALWAR BOYA" => "TALWAR BOYA",
            "TAMBALLA" => "TAMBALLA",
            "TAMBAT" => "TAMBAT",
            "TAMBLI" => "TAMBLI",
            "TARAL" => "TARAL",
            "TELAGA BALIGA " => "TELAGA BALIGA",
            "TELAGA BANAJIGA" => "TELAGA BANAJIGA",
            "TELEGU MOCHI" => "TELEGU MOCHI",
            "TELI" => "TELI",
            "TELUGU" => "TELUGU",
            "TELUGU GOWDA " => "TELUGU GOWDA",
            "TELUGU JANGAMA" => "TELUGU JANGAMA",
            "TERUVAN" => "TERUVAN",
            "TEWAR" => "TEWAR",
            "THATTAN" => "THATTAN",
            "THIGALA" => "THIGALA",
            "THIYAN " => "THIYAN",
            "THIYYA" => "THIYYA",
            "THIYYAN" => "THIYYAN",
            "THOGAJA PUSHPANJALI" => "THOGAJA PUSHPANJALI",
            "THOGATA  " => "THOGATA",
            "THOGATAGERA" => "THOGATAGERA",
            "THOGATARU" => "THOGATARU",
            "THOGATAVEERA" => "THOGATAVEERA",
            "THOGATAVEERA KSHATRIYA" => "THOGATAVEERA KSHATRIYA",
            "THOGATIGA" => "THOGATIGA",
            "THOREYA" => "THOREYA",
            "TIGALA" => "TIGALA",
            "TIGLER" => "TIGLER",
            "TILARI" => "TILARI",
            "TILVI" => "TILVI",
            "TIRALI" => "TIRALI",
            "TIRUMALI" => "TIRUMALI",
            "TIYAN " => "TIYAN",
            "TODA" => "TODA",
            "TORKE NADOR" => "TORKE NADOR",
            "TUDUG WODDAR" => "TUDUG WODDAR",
            "TULERU (BALIJA)" => "TULERU (BALIJA)",
            "TULU" => "TULU",
            "TULUVA" => "TULUVA",
            "UCHILLIAN" => "UCHILLIAN",
            "UPA NADAVAR" => "UPA NADAVAR",
            "UPA NADOR" => "UPA NADOR",
            "UPPALIGA" => "UPPALIGA",
            "UPPALIGA SHETTY" => "UPPALIGA SHETTY",
            "UPPALIYAN" => "UPPALIYAN",
            "UPPAR (BALIJA)" => "UPPAR (BALIJA)",
            "UPPARA" => "UPPARA",
            "UPPERA" => "UPPERA",
            "UPPINA KOLAGA  " => "UPPINA KOLAGA",
            "UPPU NADAR " => "UPPU NADAR",
            "UPPUNADOR " => "UPPUNADOR", 
            "URALI" => "URALI",
            "URS NAYAKA" => "URS NAYAKA",
            "USHTAMA " => "USHTAMA",
            "UTTAMA KOLAGA" => "UTTAMA KOLAGA",
            "VADDAR" => "VADDAR",
            "VADI" => "VADI",
            "VAGHRI" => "VAGHRI",
            "VAISHNAV" => "VAISHNAV",
            "VAJANTRI " => "VAJANTRI",
            "VAKKAL" => "VAKKAL",
            "VAKKALIGA" => "VAKKALIGA",
            "VALHAR" => "VALHAR",
            "VALMIKI" => "VALMIKI",
            "VALMIKIMAKKALU" => "VALMIKIMAKKALU",
            "VALVI" => "VALVI",
            "VANIYAN" => "VANIYAN",
            "VANJARA" => "VANJARA",
            "VANKAR" => "VANKAR",
            "VANNAN " => "VANNAN",
            "VANNIAR" => "VANNIAR",
            "VANNIKULA KSHATRIYA" => "VANNIKULA KSHATRIYA",
            "VARGI" => "VARGI",
            "VARLI" => "VARLI",
            "VASAVA" => "VASAVA",
            "VASAVE" => "VASAVE",
            "VASUDEV" => "VASUDEV",
            "VEDAN" => "VEDAN",
            "VEER" => "VEER",
            "VEERAMASTI" => "VEERAMASTI",
            "VEERASHIVA LINGAYATH" => "VEERASHIVA LINGAYATH",
            "VELLUTHEDAN" => "VELLUTHEDAN",
            "VETTUVAN" => "VETTUVAN",
            "VIR" => "VIR",
            "VISWA BRAHMIN" => "VISWA BRAHMIN",
            "VISWAKARMA" => "VISWAKARMA",
            "VITOLIA" => "VITOLIA",
            "VODDAR" => "VODDAR",
            "VOKKALIGA" => "VOKKALIGA",
            "WADDAR" => "WADDAR",
            "WAGIRI" => "WAGIRI",
            "WANJARI" => "WANJARI",
            "WINKAR" => "WINKAR",
            "WODDAR" => "WODDAR",
            "YADAV" => "YADAV",
            "YADAVA" => "YADAVA",
            "YAKALARA" => "YAKALARA",
            "YAKLAR" => "YAKLAR",
            "YEKKALI" => "YEKKALI",
            "YEKLAR" => "YEKLAR",
            "YELEGAL" => "YELEGAL",
            "YELLAMMALAWANDLU" => "YELLAMMALAWANDLU",
            "YERALU" => "YERALU",
            "YERAVA" => "YERAVA",
            "YERKALA" => "YERKALA",
            "YERUKALA" => "YERUKALA",
            "ZADMALLI" => "ZADMALLI",

        );
    }

    public function voucher_types()
    {
        return array("1" => "Cash", "2" => "Bank DD", "3" => "Online", "4" => "Bank Transfer", "5" => "DD");
    }
}